eKosovaInternal/Controllers/LogsController.cs
using System.Threading.Tasks;
using eKosovaInternal.Interfaces;
using eKosovaInternal.KendoFilter;
using Microsoft.AspNetCore.Mvc;

namespace eKosovaInternal.Controllers
{
	public class LogsController : Controller
	{
		private readonly ILogService _logService;

		public LogsController(ILogService logService)
		{ _logService = logService; }

		[HttpGet]
		public IActionResult Index() => View();

		[HttpGet]
		public IActionResult LogUserAuthorization() => PartialView();

		[HttpGet]
		public IActionResult LogFailedAuthentication() => PartialView();

		[HttpGet]
		public async Task<IActionResult> Read_LogUserAuthorization(DataSourceFilter data)
		{
			var dataResult = await _logService.GetLogUserAuthorization(data);
			if (dataResult.Status == 0)
				return Ok(dataResult.Data);
			else return Ok();
		}

		[HttpGet]
		public async Task<IActionResult> Read_LogFailedAuthentication(DataSourceFilter data)
		{
			var dataResult = await _logService.GetLogFailedAuthentication(data);
			if (dataResult.Status == 0)
				return Ok(dataResult.Data);
			else return Ok();
		}
	}
}

eKosovaInternal/Views/Logs/Index.cshtml
@{
	Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}
<script src="~/js/requests.js"></script>
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">Gjurmët</h4>
				<ul class="nav nav-tabs nav-justified" id="log">
					@*<li class="nav-item" data-url="@Url.Action("LogFailedAuthentication", "Logs")"><a onclick="showPartial('@Url.Action("LogFailedAuthentication", "Logs")', 'tab-content-log')" class="nav-link" data-toggle="tab">LogFailed</a></li>*@
					<li class="nav-item" data-url="@Url.Action("LogUserAuthorization", "Logs")"><a onclick="showPartial('@Url.Action("LogUserAuthorization", "Logs")', 'tab-content-log')" class="nav-link" data-toggle="tab">Hyrje/dalje</a></li>
					<li class="nav-item" data-url="@Url.Action("LogFailedAuthentication", "Logs")"><a onclick="showPartial('@Url.Action("LogFailedAuthentication", "Logs")', 'tab-content-log')" class="nav-link" data-toggle="tab">Ndalimet e qasjes</a></li>
				</ul>
				<br />
				<div id="tab-content-log">
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function () {
		var first = $('#log .nav-item').first();
		first.children('.nav-link').addClass('active show');
		loadFirstPartial(first.attr("data-url"), 'tab-content-log');
	});

	function showPartial(url, content) {
		var content = $("#" + content);
		content.fadeOut("fast", function () {
			content.html("");
			GetPartial(url).done(function (result) {
				content.html(result);
				content.fadeIn();
			});
		});
	};

	function loadFirstPartial(url, content) {
		var content = $("#" + content);
		content.fadeOut("fast", function () {
			GetEmpty(url).done(function (result) {
				content.html(result);
				content.fadeIn();
			});
		});
	};

</script>
<style>
	.nav-link {
		color: #1f1f1f !important;
	}
</style>

eKosovaInternal/Views/Logs/LogFailedAuthentication.cshtml
@{
	Layout = null;
}
<style>
	span.k-icon.k-i-calendar {
		margin-top: 14px;
	}

	button[type=submit].k-button.k-primary {
		color: #1f1f1f !important;
	}
</style>
<script src="~/kendo-files/js/kendoCulture.js"></script>
<div id="example">
	<div id="grid"></div>
	<script>
            $(document).ready(function () {
                $("#grid").kendoGrid({
                    dataSource: {
                        type: "json",
                        pageSize: 10,
                        transport: {
                            read: {
                                url: "@Url.Action("Read_LogFailedAuthentication", "Logs")",
                                type: "GET",
                                dataType: "json"
                            }
                        },
                        batch: false,
                        pageSize: 20,
                        serverPaging: true,
                        serverFiltering: true,
                    },
					height: 550,
                    filterable: {
                        mode:"menu",
						extra: false,
						operators: {
							string: {
								eq: "të barabartë me",
								contains: "përmbajnë"
							}
						},
						messages: {
							info: "Shfaq të dhëna që janë",
							clear: "Fshij",
							filter: "Filtro"
						}
					},
					toolbar: [{
						template: `<div class='d-inline-flex pull-right'>
                                <ul class="nav nav-tabs nav-tabs-bottom" style='border-bottom: 0 !important;'>
                                    <li class="nav-item" id='pdfExport'><button class="nav-link"><i class='la la-file-pdf-o'></i> PDF</button></li>
                                    <li class="nav-item" id='xlsExport'><button class="nav-link"><i class='la la-file-excel-o'></i> EXCEL</button></li>
                                </ul>
                            </div>` }],
                    editable: false,
                    pageable: true,
                    columns:
                        [{
                            field: "account",
                            title: "Përdoruesi",
                        }, {
                            field: "computerName",
                            title: "PC"
                            }, {
                                field: "ipAddress",
                                title: "IP Addresa"
                            }, {
								field: "entryDate",
								title: "Data",
								template: "#= new Date(entryDate).toLocaleString('en-GB') #",
								filterable: {
                                    extra: false,
                                    operators: {
                                        string: {
											eq: "më datën"
                                        }
                                    },
                                    ui: datePickerScript
                                }
							}
                        ]
				});
				$("#pdfExport").click(function (e) {
					var grid = $("#grid").data("kendoGrid");
					grid.saveAsPDF();
				});

				$("#xlsExport").click(function (e) {
					var grid = $("#grid").data("kendoGrid");
					grid.saveAsExcel();
				});
			});
            function datePickerScript(element) {
                    element.kendoDatePicker({
                        format: '{0: dd.MM.yyyy}',
						culture: "sq-AL",
						filterable: {
							extra: false,
							operators: {
								string: {
									eq: "më datën"
								}
							}
						}
                    })
                }
	</script>
</div>

eKosovaInternal/Views/Logs/LogUserAuthorization.cshtml
@{
	Layout = null;
}
<style>
	span.k-icon.k-i-calendar {
		margin-top: 14px;
	}

	button[type=submit].k-button.k-primary {
		color: #1f1f1f !important;
	}
</style>
<script src="~/kendo-files/js/kendoCulture.js"></script>
<div id="example">
	<div id="grid"></div>
	<script>
            $(document).ready(function () {
                $("#grid").kendoGrid({
                    dataSource: {
                        type: "json",
                        pageSize: 10,
                        transport: {
                            read: {
                                url: "@Url.Action("Read_LogUserAuthorization", "Logs")",
                                type: "GET",
                                dataType: "json"
							}
                        },
                        batch: false,
                        pageSize: 20,
                    },
					height: 550,
					filterable: {
						extra: false,
						operators: {
							string: {
								eq: "të barabartë me",
								contains: "përmbajnë"
							}
						},
						messages: {
							info: "Shfaq të dhëna që janë",
							clear: "Fshij",
							filter: "Filtro"
						}
					},
					toolbar: [{
                    template: `<div class='d-inline-flex pull-right'>
                                <ul class="nav nav-tabs nav-tabs-bottom" style='border-bottom: 0 !important;'>
                                    <li class="nav-item" id="pdfExport"><button class="nav-link"><i class='la la-file-pdf-o'></i> PDF</button></li>
                                    <li class="nav-item" id="xlsExport"><button class="nav-link"><i class='la la-file-excel-o'></i> EXCEL</button></li>
                                </ul>
                            </div>` }],
                    editable: false,
                    pageable: true,
                    columns:
						[{
                            field: "entryUser",
							title: "Përdoruesi"
                        },{
                            field: "computerName",
                            title: "Kompjuteri"
							},{
								field: "ipAddress",
								title: "IP Addresa"
							}, {
								field: "entryDate",
								title: "Data",
								template: "#= new Date(entryDate).toLocaleString('en-GB') #",
								filterable: {
									extra: false,
									operators: {
										string: {
											eq: "më datën"
										}
									},
									ui: datePickerScript
								}
							}
						]
				});
				$("#pdfExport").click(function (e) {
					var grid = $("#grid").data("kendoGrid");
					grid.saveAsPDF();
				});

				$("#xlsExport").click(function (e) {
					var grid = $("#grid").data("kendoGrid");
					grid.saveAsExcel();
				});
			});
		function datePickerScript(element) {
			element.kendoDatePicker({
				format: '{0: dd.MM.yyyy}',
				culture: "sq-AL",
				filterable: {
					extra: false,
					operators: {
						string: {
							eq: "më datën"
						}
					}
				}
			})
		}
	</script>
</div>