eKosova/Controllers/HistoryController.cs
using eKosova.Custom.Attributes;
using eKosova.Custom.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eKosova.Controllers
{
	[Authorize]
	public class HistoryController : Controller
	{
		public IActionResult Index() => View();
	}
}

eKosova/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using eKosova.Models;
using Wangkanai.Detection.Services;
using Microsoft.AspNetCore.Http;
using eKosova.Custom.Helpers;
using eKosova.Interfaces;
using System.Threading.Tasks;
using eKosova.Business;
using System;

namespace eKosova.Controllers
{
	//[RequireHttps]
	public class HomeController : Controller
	{
		private readonly IDetectionService _detectionService;
		private readonly bool isMobile;
		public HomeController(
			IDetectionService detectionService,
			IHttpContextAccessor contextAccessor)
		{
			_detectionService = detectionService;
			isMobile = _detectionService.Device.Type == Wangkanai.Detection.Models.Device.Mobile;
			LogedUser.SetHttpContextAccessor(contextAccessor);
		}
		public IActionResult Index() => View($"~/Views/Home/Index{(isMobile ? ".mobile" : "")}.cshtml");
		public IActionResult FAQ() => View($"~/Views/Home/FAQ/FAQ{(isMobile ? ".mobile" : "")}.cshtml");
		public IActionResult Help() => View($"~/Views/Home/Help/Help{(isMobile ? ".mobile" : "")}.cshtml");
		public IActionResult Contact() => View($"~/Views/Home/Contact/Contact{(isMobile ? ".mobile" : "")}.cshtml");

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

eKosova/Controllers/ProfileController.cs
using eKosova.Custom;
using eKosova.Custom.Attributes;
using eKosova.Custom.Helpers;
using eKosova.Custom.Validators;
using eKosova.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eKosova.Controllers
{
	[Authorize]
	public class ProfileController : Controller
	{
		public ProfileController(IHttpContextAccessor contextAccessor)
		{
			LogedUser.SetHttpContextAccessor(contextAccessor);
		}

		public ActionResult Index()
			=> View();

		public ActionResult Notifications(int? ID)
			=> View(ID ?? 0);

		public async Task<IActionResult> Update(ResetPassword reset)
		{
			string showMessage;
			try
			{
				if (!new PasswordUpdateValidator().Validate(reset).IsValid)
					throw new System.Exception("INVALID");

				if (!await UserHelper.UpdatePassword(reset))
					throw new System.Exception("WRONGPASS");
				showMessage = "Fjalëkalimi është ndërruar me sukses";
			}
			catch
			{
				showMessage = "Fjalëkalimi i tanishëm është gabim";
			}
			ModelState.AddModelError("Credentials", showMessage);
			return View("Index");
		}

		public async Task<IActionResult> Logout()
		{
			await UserHelper.ClearTokens(LogedUser.GetLoggedUserId());
			await HttpContext.SignOutAsync();
			//LogedUser.DeleteUserSession();
			return RedirectToAction("Index", "Home");
		}
	}
}

eKosova/Controllers/SecurityController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using eKosova.Custom.Helpers;
using eKosova.Domain;
using eKosova.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Wangkanai.Detection.Services;
using eKosova.Custom;
using eKosova.Domain.SeedWork;
using eKosova.Custom.Attributes;
using eKosova.Custom.Validators;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Newtonsoft.Json;
using eKosova.Business;

namespace eKosova.Controllers
{
	//[RequireHttps]
	[AlreadyLoggedIn]
	public class SecurityController : Controller
	{
		private readonly IDetectionService _detectionService;
		private bool isMobileDevice;
		public SecurityController(IDetectionService detectionService, IHttpContextAccessor contextAccessor)
		{
			_detectionService = detectionService;
			isMobileDevice = _detectionService.Device.Type == Wangkanai.Detection.Models.Device.Mobile;
			LogedUser.SetHttpContextAccessor(contextAccessor);
		}

		public ActionResult Index()
			=> View();

		public ActionResult Registration()
			=> View($"~/Views/Security/Registration/Registration{(isMobileDevice ? ".mobile" : "")}.cshtml");

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Verification(PartialRegister partial)
		{
			try
			{
				if (!new PartialRegisterValidator().Validate(partial).IsValid)
				{
					ModelState.AddModelError("RegistrationError", "Të dhënat nuk janë valide");
					return View($"~/Views/Security/Registration/Registration{(isMobileDevice ? ".mobile" : "")}.cshtml");
				}

				var response = await UserHelper.NewPublicUser(partial);

				if (response.Status == 0)
				{
					var repodUser = response.Data.First();
					var state = await UserHelper.AccountState(repodUser.Identification);
					return View($"~/Views/Security/Verification/Verification{(isMobileDevice ? ".mobile" : "")}.cshtml", state);
				}
				else if (response.Status == 7)
				{
					ModelState.AddModelError("Credentials", "Tashmë keni llogari në eKosova dhe mund të kyqeni");
					return View($"~/Views/Security/Index{(isMobileDevice ? ".mobile" : "")}.cshtml");
				}
				throw new Exception("kick to catch"); // every other statusCode
			}
			catch
			{
				ModelState.AddModelError("Credentials", "Regjistrimi ka dështuar. Ju lutemi provoni përsëri");
				return View($"~/Views/Security/Index{(isMobileDevice ? ".mobile" : "")}.cshtml");
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Confirmation(Images images)
		{
			try
			{
				await UserHelper.ConfirmationChecks(images);

				return View($"~/Views/Security/Confirmation/Confirmation.cshtml",
					new SMSTokenModel
					{
						Identification = images.Identification,
						Validity = (int)TimeSpan.FromMinutes(2).TotalSeconds
					});
			}
			catch (MissingFieldException)
			{
				ModelState.AddModelError("Credentials", "Dërgimi i mesazhit për verifikim ka dështuar, ju lutem provoni më vonë");
				return View($"~/Views/Security/Index{(isMobileDevice ? ".mobile" : "")}.cshtml");
			}
			catch (ObjectDisposedException)
			{
				ModelState.AddModelError("Credentials", "Llogaria juaj në eKosova është krijuar dhe ka kaluar në procesin e verifikimit. Përdorni \"Numrin Personal\" dhe \"Fjalëkalimin\" për të vazhduar më tutje.");
				return View($"~/Views/Security/Index{(isMobileDevice ? ".mobile" : "")}.cshtml");
			}
			catch (Exception e)
			{
				var message = e.Message switch
				{
					"ModelState" => "Një apo më shumë nga fotot e zgjedhura nuk janë në formatin e duhur",
					"InvalidBizDoc" => "Fotot e biznesit duhet të ngarkohen në format të pranueshëm",
					"StoringFailed" => "Ngarkimi i fotove dështoj, ju lutem provoni më vonë",
					_ => "Fotot e ngarkuara nuk mund të shfrytëzohen",
				};
				ModelState.AddModelError("Pictures", message);
				return View($"~/Views/Security/Verification/Verification{(isMobileDevice ? ".mobile" : "")}.cshtml",
					new BaseIdentification { Identification = images.Identification });
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Activation(SMSTokenModel model)
		{
			try
			{
				if (!ModelState.IsValid)
					throw new Exception("BadToken");

				var match = await UserHelper.SMSAsync(model);

				if (match)
				{
					ModelState.AddModelError("Credentials", "Llogaria juaj në eKosova është krijuar dhe ka kaluar në procesin e verifikimit. Përdorni \"Numrin Personal\" dhe \"Fjalëkalimin\" për të vazhduar më tutje.");
					return View($"~/Views/Security/Index.cshtml");
				}
				throw new Exception("BadToken"); // code doesn't match db // add counter?
			}
			catch (Exception e)
			{
				ModelState.AddModelError("Token", "Kodi nuk eshte i saktë");
				return View($"~/Views/Security/Confirmation/Confirmation.cshtml", new SMSTokenModel { Identification = model.Identification });
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Login(Credentials credentials)
		{
			try
			{
				if (!new CredentialsValidator().Validate(credentials).IsValid)
				{
					ModelState.AddModelError("Credentials", "Përdoruesi ose fjalëkalimi janë gabim");
					return View($"~/Views/Security/Index.cshtml");
				}

				var response = await UserHelper.Login(credentials);
				var repodLogin = response.Data.First();
				switch (response.Status)
				{
					case 0: // success
						var claims = new[] {
									new Claim(ClaimTypes.Name, credentials.Account),
									new Claim("Identification", repodLogin.Identification),
									new Claim("AccessToken", repodLogin.Token),
									new Claim("RefreshToken", repodLogin.RefreshToken),
									new Claim("FullName",repodLogin.First+" "+repodLogin.Last),
									new Claim("Email",repodLogin.Email ?? ""),
									new Claim("TokenValidity", repodLogin.ValidDateTimeToken.ToString()),
									new Claim("NotificationsCount",repodLogin.Notifications.Count().ToString()),
									new Claim("Notifications", JsonConvert.SerializeObject(repodLogin.Notifications))
								};
						var identity = new ClaimsIdentity(claims, "User");
						var userPrincipal = new ClaimsPrincipal(new[] { identity });
						await HttpContext.SignInAsync(userPrincipal);
						return RedirectToAction("Index", "Home");
					case 3: // photos need upload
						var state = await UserHelper.AccountState(repodLogin.Identification);
						ModelState.AddModelError("Pictures", "Fotot e cekura më poshtë duhet ngarkuar më qartë ngase nuk e kanë kaluar procesin e verifikimt");
						// add comment from db to modelerror instead of ^
						// save db comment in state
						return View($"~/Views/Security/Verification/Verification{(isMobileDevice ? ".mobile" : "")}.cshtml", state);
					case 13: // sms not verified
						var result = await UserHelper.SetToken(repodLogin.Identification);
						if (result.Validity != 0)
							return View($"~/Views/Security/Confirmation/Confirmation.cshtml",
								new SMSTokenModel { Identification = repodLogin.Identification, Validity = result.Validity });
						else
							throw new Exception("OtherStatusCodes?");
					case 1: // password wrong
					case 11: // user doesn't exist
						ModelState.AddModelError("Credentials", "Përdoruesi ose fjalëkalimi janë gabim");
						return View($"~/Views/Security/Index.cshtml");
					default: throw new Exception("OtherStatusCodes?");
				}
			}
			catch (Exception e)
			{
				ModelState.AddModelError("Credentials", "Ju lutem provoni më vonë");
				return View($"~/Views/Security/Index.cshtml");
			}
		}

		[HttpPost]
		public async Task<IActionResult> RegenSMS(string ID) => Ok(await UserHelper.SetToken(ID));

		[HttpGet]
		public ActionResult RegenPW() {
			var hashsalt = new HashSalt("123123");
			return Ok(Convert.ToBase64String(hashsalt.Salt) + " _-_-_ " + Convert.ToBase64String(hashsalt.Hash));
		}
	}
}

eKosova/Views/Home/Index.cshtml
<section class="home">
	<div class="welcome">
		<h1>Mirë se vini në platformën e shërbimeve online</h1>
		<p>
			E-Kosova është portali qeveritar ku shërbimet publike që gjenden në zyrat dhe sportelet
			fizike të institucioneve ofrohen në mënyrë elektronike.
		</p>
	</div>
	<div>
			@if (eKosova.Custom.Helpers.LogedUser.LoggedIn())
			{
				var name = eKosova.Custom.Helpers.LogedUser.GetLoggedUserFull();
				<a asp-controller="Profile" asp-action="Index" class="btn sign-up">@name</a>
				<a asp-controller="History" asp-action="Index" class="btn sign-in">Historiku</a>
			}
			else
			{
				<a asp-controller="Security" asp-action="Registration" class="btn sign-up">Regjistrohu</a>
				<a asp-controller="Security" asp-action="Index" class="btn sign-in">Hyr</a>
			}
	</div>
	<div class="card-container">
		<div class="card bg-pink">
			<div class="info-icon">
				<img src="~/images/icons/certificate.svg" alt="certificate">
			</div>
			<h1>12,193</h1>
			<p>Certifikate familjare</p>
		</div>
		<div class="card bg-yellow">
			<div class="info-icon">
				<img src="~/images/icons/insurance.svg" alt="insurance">
			</div>
			<h1>60,301</h1>
			<p>Sigurime shëndetësore</p>
		</div>
		<div class="card bg-orange">
			<div class="info-icon">
				<img src="~/images/icons/passport.svg" alt="passport">
			</div>
			<h1>34,258</h1>
			<p>Aplikime për pasaportë</p>
		</div>
		<div class="card bg-blue">
			<div class="info-icon">
				<img src="~/images/icons/payment.svg" alt="contributions">
			</div>
			<h1>8,929</h1>
			<p>Pagesa dhe kontribute</p>
		</div>
		<div class="card bg-green">
			<div class="info-icon">
				<img src="~/images/icons/driver-license.svg" alt="driver-license">
			</div>
			<h1>17,366</h1>
			<p>Aplikime për leje të vozitjes</p>
		</div>
	</div>
</section>

eKosova/Views/Home/Index.mobile.cshtml
<section class="home">
    <div class="welcome">
        <h2>Mirë se vini në platformën e shërbimeve online</h2>
        <p>
            E-Kosova është portali qeveritar ku shërbimet publike që gjenden në zyrat dhe sportelet
            fizike të institucioneve ofrohen në mënyrë elektronike.
        </p>
    </div>
    <div>
        <a asp-controller="Security" asp-action="Registration" class="btn sign-up">Regjistrohu</a>
        <a asp-controller="Security" asp-action="Index" class="btn sign-in">Hyr</a>
    </div>
    <div class="card-container">
        <div class="card bg-pink">
            <div class="info-icon">
                <img src="~/images/icons/certificate.svg" alt="certificate">
            </div>
            <h1>12,193</h1>
            <p>Certifikate familjare</p>
        </div>
        <div class="card bg-yellow">
            <div class="info-icon">
                <img src="~/images/icons/insurance.svg" alt="insurance">
            </div>
            <h1>60,301</h1>
            <p>Sigurime shëndetësore</p>
        </div>
        <div class="card bg-orange">
            <div class="info-icon">
                <img src="~/images/icons/passport.svg" alt="passport">
            </div>
            <h1>34,258</h1>
            <p>Aplikime për pasaportë</p>
        </div>
        <div class="card bg-blue">
            <div class="info-icon">
                <img src="~/images/icons/payment.svg" alt="contributions">
            </div>
            <h1>8,929</h1>
            <p>Pagesa dhe kontribute</p>
        </div>
        <div class="card bg-green">
            <div class="info-icon">
                <img src="~/images/icons/driver-license.svg" alt="driver-license">
            </div>
            <h1>17,366</h1>
            <p>Aplikime për leje të vozitjes</p>
        </div>
    </div>
</section>

eKosova/Views/Home/Test.cshtml
<section class="confirmation">
	<div class="title">
		<h2>Konfirmimi</h2>
	</div>
	@using (Html.BeginForm("Activation", "Security", FormMethod.Post))
	{
		<input type="hidden" value="1" name="Identification" />
		<div class="d-inline-flex p-relative justify-space-between w-100">
			<div class="confirm-code w-100">
				<label for="confirm-code" class="d-block mb-10">Shkruani kodin e konfirmimit që keni pranuar përmes SMS-it</label>
				<input id="confirm-code" class="d-block w-100" name="SMSToken" data-mask="00000" required>
			</div>
		</div>
		<button class="btn-continue" type="submit">VAZHDO</button>
	}
	<span class="error-message">@Html.ValidationMessage("Token")</span>
	<div><p>Vlefshmëria e kodit konfirmues: <span id="smsCounter" class="attention"></span></p></div>
	<div id="resend">
		Nëse SMS-in me kodin konfirmues nuk e keni pranuar brenda dy (2) minutave atëherë klikoni <span id="regenToken" class="attention pointer">këtu</span> që të ridërgoni kodin konfirmues.
	</div>
</section>
<script src="~/js/countdown.js"></script>
<script>
	count(120, 'smsCounter', 'resend');
	$('#regenToken').click(function () {
		$.post('https://localhost:5001/Security/RegenSMS?ID=1')
	});
</script>