eKosova/Controllers/InformationsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using eKosova.Custom.Helpers;
using eKosova.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Wangkanai.Detection.Services;

namespace eKosova.Controllers
{
	//[RequireHttps]
	public class InformationsController : Controller
	{
		private readonly IInformationViewService _informationViewService;
		private readonly IDetectionService _detectionService;
		private bool isMobile;
		private readonly IMemoryCache _cache;

		public InformationsController(IInformationViewService informationViewService, IDetectionService detectionService, IMemoryCache cache, IHttpContextAccessor contextAccessor)
		{
			_informationViewService = informationViewService;
			_detectionService = detectionService;
			isMobile = _detectionService.Device.Type == Wangkanai.Detection.Models.Device.Mobile;
			_cache = cache;
			LogedUser.SetHttpContextAccessor(contextAccessor);
		}

		public IActionResult Index() => View("Index" + (isMobile ? ".mobile" : ""));

		public IActionResult Open(int ID) => View("Open" + (isMobile ? ".mobile" : ""), ID);

		public async Task<IActionResult> Data()
		{
			try
			{
				if (!_cache.TryGetValue(CacheKeys.Informations, out IList<Domain.Informations.Information> informations))
				{
					informations = (await _informationViewService.GetInformations()).Data;
					_cache.Set(CacheKeys.Informations, informations, CacheKeys.Options);
				}
				return Ok(informations);
			}
			catch { return Ok(); }
		}
	}
}

eKosova/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using eKosova.Custom.Helpers;
using eKosova.Domain.ServiceCategories;
using eKosova.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Wangkanai.Detection.Services;

namespace eKosova.Controllers
{
	public class ServicesController : Controller
	{
		private readonly IMemoryCache _cache;

		private readonly IServiceCategoryViewService _viewService;

		private readonly IDetectionService _detectionService;

		private readonly bool isMobile;

		public ServicesController(IDetectionService detectionService, IServiceCategoryViewService viewService, IMemoryCache memoryCache, IHttpContextAccessor contextAccessor)
		{
			_detectionService = detectionService;
			isMobile = _detectionService.Device.Type == Wangkanai.Detection.Models.Device.Mobile;
			_viewService = viewService;
			_cache = memoryCache;
			LogedUser.SetHttpContextAccessor(contextAccessor);
		}

		public ActionResult Index() => View();

		[Route("Service/{service}")]
		public ActionResult Service(int service) => View($"~/Views/Services/SubServices/SubServices{(isMobile ? ".mobile" : "")}.cshtml", service);

		public async Task<IActionResult> Data()
		{
			try
			{
				if (!_cache.TryGetValue(CacheKeys.Services, out IList<ServiceCategory> services))
				{
					services = (await _viewService.GetServices()).Data;
					_cache.Set(CacheKeys.Services, services, CacheKeys.Options);
				}
				return Ok(services);
			}
			catch { return Ok(); }
		}

		[Route("Service/{service}/Data")]
		public async Task<IActionResult> SubServicesData(int service)
		{
			if (!_cache.TryGetValue(CacheKeys.SubServices + service, out IList<ServiceSubCategory> subCategories))
			{
				subCategories = (await _viewService.GetSubServices(service)).Data;
				_cache.Set(CacheKeys.SubServices + service, subCategories, CacheKeys.Options);
			}
			return Ok(subCategories);
		}

		public ActionResult PaymentInfo() => View($"~/Views/Services/PaymentInfo/PaymentInfo{(isMobile ? ".mobile" : "")}.cshtml");
		public ActionResult OnlinePayment() => View($"~/Views/Services/OnlinePayment/OnlinePayment{(isMobile ? ".mobile" : "")}.cshtml");
		public ActionResult ConfirmPayment() => View($"~/Views/Services/ConfirmPayment/ConfirmPayment{(isMobile ? ".mobile" : "")}.cshtml");
	}
}

eKosova/Views/Shared/_HelpIcons.cshtml
<div class="p-fixed fixed-icons">
    <a href="#"><img class="listen-audio" src="~/images/icons/face.svg" alt="listen"></a>
    <a href="#"><img class="play-video" src="~/images/icons/play.svg" alt="play video"></a>
</div>

eKosova/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>eKosova Portal</title>
	<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
		  rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="~/css/style.css">
	<script src="~/js/jquery-3.5.0.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
</head>

<body>
	<div class="loader">
		<img src="~/images/icons/loading.svg" alt="loading">
		<h3>Ju lutem prisni, kërkesa juaj është në proces e sipër.</h3>
	</div>
	<header>
		<div class="top-bar">
			<a asp-controller="Home" asp-action="Help">Ndihmë</a>
			<a asp-controller="Home" asp-action="FAQ">FAQ</a>
			<a asp-controller="Home" asp-action="Contact">Kontakti</a>
			<a href="https://mail.rks-gov.net/owa/" target="_blank">Webmail</a>
			<p class="push">Gjuha:</p>
			<a href="#">Shq</a>
			<a href="">Eng</a>
			<a href="">Srb</a>
		</div>
		<div class="menu">
			<a asp-controller="Home" asp-action="Index"><div id="logo"></div></a>
			<nav class="push">
				<ul>
					<li><a asp-controller="Home" asp-action="Index">Kryesore</a></li>
					<li><a asp-controller="Services" asp-action="Index">Shërbime</a></li>
					<li><a asp-controller="Informations" asp-action="Index">Informata</a></li>
				</ul>
			</nav>
		</div>
	</header>

	<div class="container">
		@RenderBody()
	</div>

	<footer>
		<div class="footer-content">
			<div class="item">
				<a href="#">Rreth portalit</a>
				<a href="#">Privatësia</a>
				<a href="#">Kushtet e përdorimit</a>
			</div>
			<div class="item">
				<p>Kontakti</p>
				<p>0800 888 880</p>
				<div class="social-icons">
					<img src="~/images/icons/fb.svg" alt="facebook">
					<img src="~/images/icons/twitter.svg" alt="twitter">
					<img src="~/images/icons/instagram.svg" alt="instagram">
				</div>
			</div>
			<div class="item">
				<a href="#" class="android"><img src="~/images/Google_Play_Store_Badge.svg" alt="Get it on Google Play"></a>
				<a href="#" class="ios"><img src="~/images/Download_on_the_App_Store_Badge.svg" alt="Download on the App Store"></a>
			</div>
			<div class="item last">
				@*<p>Republika e Kosovës</p>
					<p>Agjecia e shoqërisë së informacionit</p>
					<p>Implementuar nga &nbsp;<img id="pbc-logo" src="~/images/icons/pbc.svg" alt="pbc logo"></p>*@
				<img id="pbc-logo" src="~/images/icons/pbc.svg" alt="pbc logo">
			</div>
		</div>
	</footer>
	<script src="~/lib/jquery-mask/jquery.mask.min.js"></script>
	<script src="~/js/site.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

eKosova/Views/Shared/_Layout.mobile.cshtml
@using eKosova.Custom.ExtensionMethods
@{ 
    string actionResult = this.ViewContext.RouteData.Values["action"].ToString().ToLower();
}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>eKosova Portal</title>

    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/css/style.mobile.css">
    <script src="~/js/jquery-3.5.0.min.js"></script>
    <script src="~/lib/jquery-mask/jquery.mask.min.js"></script>
</head>

<body>
    <div class="loader">
        <img src="~/images/icons/loading.svg" alt="loading">
        <h3>Ju lutem prisni, kërkesa juaj është në proces e sipër.</h3>
    </div>
    @if (new string[] { "registration", "verification", "faq" }.Any(_ => _ == actionResult))
    {
        await Html.RenderPartialAsync("~/Views/Shared/_HelpIcons.cshtml");
    }
    <div class="mobile-menu">
        <div class="menu">
            <div id="logo">
                <a asp-controller="Home" asp-action="Index">
                    <span>eKo</span><span style="color: #7c92c9">sova</span>
                </a>
            </div>
            <div class="menu-toggle">
                <div class="menu-icon"></div>
            </div>
        </div>
        <div class="mobile-nav">
            <a class="menu-home" asp-controller="Home" asp-action="Index">Kryesore</a>
            <a class="menu-services" asp-controller="Services" asp-action="Index">Shërbime</a>
            <a class="menu-informations" asp-controller="Informations" asp-action="Index">Informata</a>
            <a class="menu-help" asp-controller="Home" asp-action="Help">Ndihmë</a>
            <a class="menu-faq" asp-controller="Home" asp-action="FAQ">FAQ</a>
            <a class="menu-contact" asp-controller="Home" asp-action="Contact">Kontakti</a>
            <div>
                <platform include="android"><a href="#"><img class="app-icon" src="~/images/Google_Play_Store_Badge.svg" alt="Get it on Google Play"></a></platform>
                <platform include="ios"><a href="#"><img class="app-icon" src="~/images/Download_on_the_App_Store_Badge.svg" alt="Download on the App Store"></a></platform>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>

    <footer>
        <div class="item mobile-app">
            <platform include="android"><a href="#"><img src="~/images/Google_Play_Store_Badge.svg" alt="Get it on Google Play"></a></platform>
            <platform include="ios"><a href="#"><img src="~/images/Download_on_the_App_Store_Badge.svg" alt="Download on the App Store"></a></platform>
        </div>
        <div class="item">
            <a href="#">Rreth portalit</a>
            <a href="#">Privatësia</a>
            <a href="#">Kushtet e përdorimit</a>
        </div>
        <div class="item">
            <p>Kontakti</p>
            <p><a href="tel:0800 888 880">0800 888 880</a></p>
            <div class="social-icons">
                <a href="#"><img src="~/images/icons/fb.svg" alt="facebook"></a>
                <a href="#"><img src="~/images/icons/twitter.svg" alt="twitter"></a>
                <a href="#"><img src="~/images/icons/instagram.svg" alt="instagram"></a>
            </div>
        </div>
        <div class="item language">
            <p>Gjuha aktive:</p>
            @Html.CustomDropdown("Language", new SelectListItem[] {
           new SelectListItem() { Text = "Shqip", Value = "1", Selected = true },
           new SelectListItem() { Text = "Serbisht", Value = "2" },
           new SelectListItem() { Text = "Anglisht", Value = "3" },
       }, "Zgjedh gjuhën", null)
        </div>
        <div class="item last">
            @*<p>Agjecia e shoqërisë së informacionit</p>
                <p>Republika e Kosovës</p>
                <p>Implementuar nga &nbsp;<img id="pbc-logo" src="~/images/icons/pbc.svg" alt="pbc logo"></p>*@
            <img id="pbc-logo" src="~/images/icons/pbc.svg" alt="pbc logo">
        </div>
    </footer>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)

    <script>
        (function () {
            var menuToggle = document.querySelector('.menu-toggle'),
                menu = document.querySelector('.mobile-menu'),
                body = document.querySelector('body');


            menuToggle.onclick = function () {
                menu.classList.toggle('menu-opened');
                body.classList.toggle('menu-opened');
            }
        }());
    </script>
</body>
</html>